### ISSUE TITLE
请开放tquic源码

### ISSUE THREAD

**Issue by alexliyu7352** [TencentCloud/libtquic-sdk#2]
光是给静态库毫无用处阿, 应该开放源码才对.
否则怎么二次定制?

**Comment by ForgetAll** [comment]
+1

**Comment by alexliyu7352** [comment]
至少你不开放源码, 也类似bilibili一样, 开放个样板裁剪项目.
让我们学习下如何进行裁剪, 我自己也裁剪了cronet, 但是裁剪到2.7mb就实在无从下手了.
而且移植到android上, 还需要修改大量的代码, 去掉依赖java库.

所以很希望能学习下大厂大佬怎么搞的.

ForgetAll ***@***.***> 于2022年1月12日周三 15:20写道：

**Comment by tk1061178** [comment]
谢谢关注，代码侧的开源还在筹划中哈，当前的lib可以用于直接集成使用。
