### ISSUE TITLE
可以大致写下如何裁剪cronet的吗

### ISSUE THREAD

**Issue by pluto-junzeng** [TencentCloud/libtquic-sdk#3]
开源so。。。。

**Comment by alexliyu7352** [comment]
很麻烦, 主要就是一个是在gn生成项目时去掉一些依赖的组件, 如websocket, ftp等之类的.
这个配置gn args的时候可以.

另外就是去掉测试的相关代码, 这一步也不难.
最难的就是接下去的进一步裁剪,
需要分析每个cronet的源文件, 去掉没必要的源文件.
然后在分析cronet引用的文件中, 去掉没必要的文件.

最后就是代码级别的裁剪了, 
一些流程判断或者调用的类, 其实没有必要使用.
比如一些上报数据的阿, 一些统计类的阿之类的.
这些都需要删除掉这些代码或者精简掉这些代码.

如果要做跨平台, 那么就还需要一个一个的流程去跟踪.比如移植到android上, 你就要重新写一些新的接口和类.
完成android jni的初始化, 而不能直接使用.还需要去掉base模块中android平台的一些依赖的java包等等.

总之这玩意想要弄好, 很复杂.特别是编译每次都好慢, 调试又不好调试.
需要花费大量的时间来进行调试才能进一步的裁剪.
特别是要裁剪成一个跨平台的类库, 还需要在整个项目的base/net模块中修改不少的代码才行.总之很麻烦, 特别是编译, 
我32g的内存的机器, 每次都被折腾到大量的使用swap缓存了. 

所以看到这个项目眼前一亮..
但是估计就是一个kpi项目了., 没办法开放更多的让你定制的部分了.

其实cronet要使用好, 在协议参数部分以及证书验证, 加密等部分需要定制的更多.特别是一些需要用到私有协议的.

哎.....看来只能自己慢慢搞了.

**Comment by pluto-junzeng** [comment]
Good

**Comment by tk1061178** [comment]
谢谢关注，同上一个issue，代码的开源在筹备中哈
