### ISSUE TITLE
腾讯云付费了，这个客户端SDK有人维护么？有问题请教

### ISSUE THREAD

**Issue by jerry-mengbo** [TencentCloud/libtquic-sdk#4]

**Comment by tk1061178** [comment]
可以的，有任何问题可以在issue里提出来

**Comment by 1443213244** [comment]
项目目前只有sdk提供，有考虑像阿里的xquic一样开放源码吗？

**Comment by tk1061178** [comment]
> 项目目前只有sdk提供，有考虑像阿里的xquic一样开放源码吗？

这块我们准备做一次较大的重构，重构内容包含对外开源，因此这次没有放出源码。当前想了解源码可以参考google quiche库。
